pessoa/urls.py
from django.contrib import admin
from django.urls import path
from . import views

##http://localhost:8000/pessoa/incluir
##http://localhost:8000/pessoa/listar
urlpatterns = [
         ## URL     ## nome função               chamada interna
    path('incluir',views.insert_pessoa,name='insert_pessoa'),
    path('alterar/<int:id>',views.update_pessoa,name='update_pessoa'),
    path('excluir/<int:id>',views.delete_pessoa,name='delete_pessoa'),
    path('consultar/<int:id>',views.view_pessoa,name='view_pessoa'),
    path('listar',views.list_pessoa,name='list_pessoa'),
]

projeto/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pessoa/', include('pessoa.urls')),
]

core/models.py
from django.db import models

# Create your models here.

pessoa/models.py
from django.db import models

# Create your models here.

class PessoaModel(models.Model):
    pessoa_id = models.AutoField(primary_key=True)
    pessoa_nome = models.CharField(
        max_length=100,
        null=False,
        blank=False,
        verbose_name="Nome")
    pessoa_logradouro = models.CharField(
        max_length=100,
        null=False,
        blank=False,
        verbose_name="Logradouro")
    pessoa_numero = models.CharField(
        max_length=5,
        null=False,
        blank=False,
        verbose_name="Número")

    class Meta:
        ordering = ['pessoa_nome']
        verbose_name = 'Pessoa'
        verbose_name_plural = 'Pessoas'

    def __str__(self):
        return self.pessoa_nome


class ContatoModel(models.Model):
    
    contato_id = models.AutoField(primary_key=True)
    contato_telefone = models.CharField(
                       max_length=15,
                       null=False,
                       blank=False,
                       verbose_name="Telefone")
    pessoa = models.ForeignKey(PessoaModel, on_delete=models.CASCADE)
                    

pessoa/forms.py
from django import forms
from .models import PessoaModel

class PessoaForm(forms.ModelForm):
    pessoa_nome = forms.CharField(required=True, label="Nome")
    pessoa_logradouro = forms.CharField(required=True, label="Logradouro")
    pessoa_numero = forms.CharField(required=True, label="Número")

    class Meta:
        model = PessoaModel
        fields = [
            'pessoa_nome',
            'pessoa_logradouro',
            'pessoa_numero'
        ]
        
        
class ContatoForm(forms.ModelForm):
    
    contato_telefone = forms.CharField(label="Telefone")
    pessoa = forms.ModelChoiceField(queryset=PessoaModel.objects.all(), label="Contato")
    

core/views.py
from django.shortcuts import render

# Create your views here.

pessoa/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import PessoaForm
from .models import PessoaModel

##from django.http import HttpResponse

# Create your views here.

def list_pessoa(request):
    form = PessoaModel.objects.all() ##ler a tabela pessoa
    context = {
        'form':form,
    }
    return render(request, 'listar.html', context)

def insert_pessoa(request):
    form = PessoaForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('list_pessoa')
    context = {
        'form':form
    }
    return render(request, 'novo3.html',context)

def update_pessoa(request, id):
    pessoa = get_object_or_404(PessoaModel, pessoa_id=id)
    form = PessoaForm(request.POST or None, instance = pessoa)
    if form.is_valid():
        form.save()
        return redirect('list_update')
    context = {
        'form':form,
    }
    return render(request, 'novo2.html', context)


def delete_pessoa(request, id):
    pessoa = get_object_or_404(PessoaModel, pessoa_id=id)
    form = PessoaForm(request.POST or None, instance = pessoa)
    if request.method == 'POST':
        pessoa.delete()
        return redirect('list_pessoa')
    context={
        'form':form,
    }
    return render(request, 'novo2.html', context)


def view_pessoa(request, id):
    pessoa = get_object_or_404(PessoaModel, pessoa_id=id)
    form = PessoaForm(request.POST or None, instance = pessoa)
    if request.method == 'POST':
        return redirect('list_pessoa')
    context={
        'form':form,
    }
    return render(request, 'novo2.html', context)

core/templates/base.html
{%load static%}
<!doctype html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css'%}">
    <link rel="stylesheet" href="{% static 'css/font-awesome.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-datepicker.standalone.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/footer.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}" >

    <title>{% block title %}{% endblock %}</title>
</head>
<body>
     <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
      <a class="navbar-brand" href="#">Navbar</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Link</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Dropdown
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="#">Action</a>
              <a class="dropdown-item" href="#">Another action</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="#">Something else here</a>
            </div>
          </li>
        </ul>
      </div>
    </nav>
      <div class="container-fluid">
          <div class="jumbotron">
             {%block main%}
             {%endblock%}
          </div>
      </div>


    <footer class="footer">
       <div class="container-fluid">
         <span class="text-muted">IFSP Instituto Federal de Educação Ciência e Tecnologia de São Paulo</span>
       </div>
   </footer>
   <script src="{% static 'js/jquery-1.10.2.min.js' %}"></script>
   <script src="{% static 'js/jquery.mask.min.js' %}"></script>
   <script src="{% static 'js/jquery.maskMoney.min.js' %}"></script>
   <script src="{% static 'js/bootstrap.js' %}"></script>
   <script src="{% static 'js/bootstrap-datepicker.min.js' %}"></script>
   <script src="{% static 'js/bootstrap-datepicker.pt-BR.min.js' %}"></script>
</body>
</html>

pessoa/templates/listar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" >
    <title>Title</title>
</head>
<body>
<div class="container">
    <div class="table-responsive">
        <table class="table
                      table-striped
                      table-bordered
                      table-hover
                      table-collapse">
         <thead>
            <tr>
                <th>Nome</th>
                <th>Logradouro</th>
                <th>número</th>
                <th>Ações</th>
            </tr>
         </thead>
         <tbody>
            {%for p in form%}
            <tr>
                <td>{{ p.pessoa_nome }}</td>
                <td>{{ p.pessoa_logradouro }}</td>
                <td>{{ p.pessoa_numero }}</td>
				<td class="text-center">
				  <a id="idAlterar" class="btn btn-warning btn-sm"
				     title="Alterar dados da pessoa"
					 href="{% url 'update_pessoa' p.pessoa_id%}">
                     <i class="fa fa-pencil-square" aria-hidden="true"></i>
            	  </a>
				  <a id="idExcluir" class="btn btn-danger btn-sm"
				     title="Excluir dados da pessoa"
					 href="{% url 'delete_pessoa' p.pessoa_id%}">
                     <i class="fa fa-trash-o" aria-hidden="true"></i>
				  </a>
                  <a id="idConsultar" class="btn btn-info btn-sm"
				     title="Consultar dados da pessoa"
					 href="{% url 'view_pessoa' p.pessoa_id%}">
                     <i class="fa fa-eye" aria-hidden="true"></i>
				  </a>
				</td>
            </tr>
            {%endfor%}
         </tbody>
        </table>
        <a id="idIncluir" class="btn btn-primary" href="{% url 'insert_pessoa' %}">Nova Pessoa <i class="fa fa-check-square-o" aria-hidden="true"></i></a>


    </div>


</div>

</body>
</html>

pessoa/templates/novo.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Cadastro de Pessoa</title>
</head>
<body>

    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Salvar</button>
    </form>

</body>
</html>

pessoa/templates/novo1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>Title</title>
</head>
<body class="container">
<div class="jumbotron">
  <div class="page-header">
      <h2>Cadastro</h2>
  </div>
  <form class="form-horizontal" role="form" method="post" >
      <div class="row">
          <div class="col-sm-10">
              <div class="form-group">
                    <label for="pessoa_nome"
                           class="control-label">Nome</label>
                    <input id="pessoa_nome"
                           type="text"
                           name="pessoa_nome"
                           value="{{ pessoa_nome }}"
                           class="form-control" />
              </div>
          </div>
      </div>
      <div class="row">
          <div class="offset-sm-2">
              <button type="submit"
                      class="btn btn-primary">Salvar</button>
          </div>
      </div>
  </form>
</div>
</body>
</html>

pessoa/templates/novo2.html
{% extends "base.html" %}

{%load bootstrap%}

{%block main%}
   <form class="form-horizontal" role="form" method="post" >
       {%csrf_token%}
       <!--{{form|bootstrap}}-->
       {{form|bootstrap_horizontal:'col-sm-1'}}
       <div class="row">
          <div class="form-group">
	          <div class="offset-sm-2">
	              <button type="submit"
	                      class="btn btn-primary">Salvar</button>
	          </div>
          </div>
      </div>
  </form>
{%endblock%}

pessoa/templates/novo3.html
{% extends "base.html" %}

{% load widget_tweaks %}

{%block main%}

<form class="form-horizontal" role="form" method="post" >
       {%csrf_token%}
  
       <div class="row">
	       <div class="col-sm-6">
	          <div class="form-group {% if field.errors %} has-error {%endif%}">
	          <label for="id_pessoa_nome" 
	                 class="col-sm-2 control-label">{{form.pessoa_nome.label}}</label>
	                 {% render_field form.pessoa_nome class='form-control'%}
	                 {% for error in form.pessoa_nome.errors %}
	                    <span class="help-block">{{error}}</span>
	                 {% endfor %} 
	          </div>
	       </div>
	       <div class="col-sm-6">
	          <div class="form-group {% if field.errors %} has-error {%endif%}">
	          <label for="id_pessoa_logradouro" 
	                 class="col-sm-2 control-label">{{form.pessoa_logradouro.label}}</label>
	                 {% render_field form.pessoa_logradouro class='form-control'%}
	                 {% for error in form.pessoa_logradouro.errors %}
	                    <span class="help-block">{{error}}</span>
	                 {% endfor %} 
	          </div>
	       </div> 
       </div> 
  
  
       <div class="row">
          <div class="form-group">
	          <div class="offset-sm-2">
	              <button type="submit"
	                      class="btn btn-primary">Salvar</button>
	          </div>
          </div>
      </div>
  </form>

{%endblock%}